# Generated by Django 5.1.1 on 2024-10-07 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_pair'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10)),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('risk', models.DecimalField(decimal_places=2, max_digits=5)),
                ('risk_type', models.CharField(max_length=10)),
                ('position', models.DecimalField(decimal_places=2, max_digits=10)),
                ('position_type', models.CharField(max_length=10)),
                ('pair', models.CharField(max_length=10)),
                ('trade_type', models.CharField(max_length=5)),
                ('entry_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('stop_loss', models.DecimalField(decimal_places=4, max_digits=10)),
                ('fee', models.DecimalField(decimal_places=4, max_digits=5)),
                ('target_choice', models.CharField(max_length=5)),
                ('calculated_leverage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calculated_position', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
