# Generated by Django 5.1.1 on 2024-10-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_journalentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='win',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=3),
        ),
    ]
