# Generated by Django 5.1.1 on 2024-10-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_journalentry_win'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='target_price',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
    ]
