# Generated by Django 5.1.1 on 2024-10-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_journalentry_target_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='target_choice',
            field=models.CharField(max_length=20),
        ),
    ]
