# Generated by Django 5.1.1 on 2024-10-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_journalentry_target_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='win',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], default='', max_length=3, null=True),
        ),
    ]
