# Generated by Django 5.1.1 on 2024-10-10 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_journalentry_win'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='win',
        ),
    ]
