# Generated by Django 5.1.1 on 2024-10-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_journalentry_win'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='pnl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
