# Generated by Django 5.1.1 on 2024-10-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_journalentry_pnl'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='calculated_risk_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='calculated_win_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
