# Generated by Django 5.1.1 on 2024-10-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_journalentry_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
