# Generated by Django 5.1.1 on 2024-10-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_journalentry_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalentry',
            old_name='created_at',
            new_name='entry_date',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='exit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
