# Generated by Django 5.1.1 on 2024-10-22 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_rename_created_at_journalentry_entry_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('timeframe', models.CharField(max_length=10)),
                ('indicators', models.CharField(max_length=255)),
                ('entry_rules', models.TextField()),
                ('exit_rules', models.TextField()),
                ('type', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='backend.strategy')),
            ],
        ),
    ]
