# Generated by Django 5.1.1 on 2024-10-23 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_strategy_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.strategy'),
        ),
    ]
