# Generated by Django 5.1.1 on 2024-10-24 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_journalentry_strategy'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntryAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='journal_entry_attachments/')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='backend.journalentry')),
            ],
        ),
    ]
